### ISSUE TITLE
Scrollbar on AppNavigation

### ISSUE THREAD

**Issue by gary-kim** [nextcloud-libraries/nextcloud-vue#829]
In the Calendar, opening or closing the settings introduces the scollbar for a second so the `+ New event` and other buttons shrinks a bit for a split second.

![output](https://user-images.githubusercontent.com/47195730/72710320-cb038380-3ba1-11ea-9b02-473f63612038.gif)

Having `overflow-y: hidden;` would fix the issue but it looks like it is set to `auto` explicitly. Was that intentional? Maybe add the overflow-y as a configurable prop in case an app wants the scrollbar?

I can make the PR.

https://github.com/nextcloud/nextcloud-vue/blob/88c062728fb6b2df6977b45aa32e4e61b109c7e5/src/components/AppNavigation/AppNavigation.vue#L46

cc @skjnldsv @georgehrke

**Comment by korelstar** [comment]
You can't know if you app navigation is longer than

**Comment by korelstar** [comment]
Sorry, I fall over my keyboard. What I wanted to say: you can't know if your navigation is longer than available room. Hence overflow must be auto. The issue has to be solved using another fix.

**Comment by jotoeri** [comment]
@gary-kim Does removing the `height: 100%` on the `ul` fix your issue? Could be it doesn't need to re-render the 100% then...?
So this would also be solved by #1123?

**Comment by mejo-** [comment]
Out of curiosity I just tried to reproduce the issue with the Calendar app on Nextcloud 27.1.3 (with Firefox 119 on Linux as browser). I wasn't able to reproduce this bug. Do others still face it?

**Comment by skjnldsv** [comment]
Might be fixed with time and the various changes.
Also we're stepping away from the sliding settings for a modal :+1:

**Comment by mejo-** [comment]
Let's close the issue then. If anybody still faces the issue, don't hesitate to comment and/or reopen.
